<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>KEJVAULT | Secure African Commerce</title>
    <meta name="description" content="Secure the deal. Protect the payment.">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
<main id="top">
    <section class="hero">
        <nav class="nav shell">
            <a class="brand" href="#top"><span class="brand-mark">K</span> KEJVAULT</a>
            <div class="nav-links"><a href="#how">How it works</a><a href="#wallet">Wallet</a><a href="#business">Business</a><a href="#security">Security</a></div>
            <a class="button button-primary nav-cta" href="#demo">Start securely <span>-&gt;</span></a>
            <button class="menu-button" aria-label="Toggle navigation" aria-expanded="false">&#9776;</button>
        </nav>
        <div class="hero-grid shell">
            <div class="hero-copy">
                <p class="eyebrow eyebrow-light">[+] The trust layer for African commerce</p>
                <h1>Buy with confidence.<br><em>Sell without worry.</em></h1>
                <p class="hero-text">KEJVAULT protects transactions between buyers and sellers, helping businesses and individuals trade with greater confidence across African markets.</p>
                <div class="hero-actions"><a class="button button-primary large" href="#demo">Start trading securely <span>-&gt;</span></a><a class="button button-ghost large" href="#how">How KEJVAULT works</a></div>
                <div class="flow"><div><span class="flow-icon">B</span><small>BUYER</small></div><b>-&gt;</b><div class="secure"><span>K</span><small>KEJVAULT</small></div><b>-&gt;</b><div><span class="flow-icon">S</span><small>SELLER</small></div></div>
            </div>
            <div class="phone-wrap"><div class="phone-glow"></div><div class="phone"><div class="phone-head"><strong>KEJVAULT</strong><span class="ok">OK</span></div><small class="muted">Available balance</small><div class="balance">1,250,000 <small>XOF</small></div><small class="muted caps">Demo data</small><div class="mini-stats"><div><small>Protected</small><strong>8 deals</strong></div><div><small>Pending release</small><strong>245,000</strong></div></div><div class="activity"><div><i>K</i><span><strong>500,000 XOF</strong><small>Payment secured</small></span><b>&gt;</b></div><div><i>B</i><span><strong>120,000 XOF</strong><small>Purchase</small></span><b>&gt;</b></div><div><i>+</i><span><strong>250,000 XOF</strong><small>Payment released</small></span><b>&gt;</b></div></div></div></div>
        </div>
    </section>

    <section class="section problem"><div class="shell two-col"><div><p class="eyebrow">The problem</p><h2>Trust should never be the biggest risk in a transaction.</h2></div><div class="risk-grid">@foreach(['Paying before receiving','Shipping before payment','Remote transactions','Unknown sellers','Fake payment proofs','Buyer-seller disputes','Social commerce fraud','Marketplace uncertainty'] as $risk)<div><span>x</span>{{ $risk }}</div>@endforeach</div></div><div class="shell callout"><span>OK</span> KEJVAULT creates a trusted layer between the buyer and the seller.</div></section>

    <section id="how" class="section"><div class="shell"><p class="eyebrow">How it works</p><div class="section-intro"><h2>A clear path from agreement to payment.</h2><p>Funds move only after the transaction conditions are confirmed under the applicable service rules.</p></div><div class="steps">@foreach([['01','Buyer creates a transaction','Product, amount, seller, and deal conditions are added.'],['02','Buyer pays KEJVAULT','Funds are placed in a secured transaction under the service rules.'],['03','Seller completes the deal','The seller sees that payment is secured, then delivers.'],['04','Payment is released','Once the agreed conditions are confirmed, funds are released.']] as $step)<article><strong>{{ $step[0] }}</strong><h3>{{ $step[1] }}</h3><p>{{ $step[2] }}</p></article>@endforeach</div></div></section>

    <section id="demo" class="section dark-section"><div class="shell"><div class="section-intro light"><div><p class="eyebrow eyebrow-light">Live product story</p><h2>See how a KEJVAULT transaction works.</h2></div><p>Follow a sample purchase from agreement to release. All people, values, and activity shown here are fictional.</p></div><div class="demo-card"><div class="demo-summary"><span class="tag">Interactive demo</span><p class="muted">Product</p><h3>iPhone 15 Pro</h3><div class="buyer-seller"><div><small>Buyer</small><strong>John</strong></div><div><small>Seller</small><strong>Marketplace Store</strong></div></div><div class="transaction"><small>Transaction value</small><strong>650,000 XOF</strong></div><span class="secured">OK &nbsp; FUNDS SECURED</span><div class="demo-actions"><button id="next-step" class="button button-primary">Next step <span>-&gt;</span></button><button id="restart-demo" class="icon-button" aria-label="Restart demonstration">R</button></div></div><div class="timeline" id="timeline">@foreach(['John creates the transaction','John pays 650,000 XOF','KEJVAULT secures the funds','Seller receives confirmation','Seller ships the product','John receives the product','John confirms receipt','KEJVAULT releases 650,000 XOF'] as $index => $item)<button class="timeline-item {{ $index < 2 ? 'done' : ($index === 2 ? 'active' : 'pending') }}" data-step="{{ $index }}"><span>{{ $index < 2 ? 'OK' : $index + 1 }}</span>{{ $item }}<i></i></button>@endforeach</div></div></div></section>

    <section class="section"><div class="shell"><p class="eyebrow">The KEJVAULT difference</p><h2>More than a payment. It is a trusted transaction.</h2><div class="feature-grid">@foreach([['K','Secure transactions','Protect your money while the transaction is being completed.'],['OK','Buyer protection','Reduce the risk of paying an unknown seller before receiving your order.'],['U','Seller protection','Know that funds are secured before completing the transaction.'],['W','Digital wallet','Keep track of balances and transactions from one place.'],['M','Mobile Money','Move your funds to supported Mobile Money services.'],['H','Transaction history','Keep a clear digital record of your payments and transactions.']] as $feature)<article><span class="feature-icon">{{ $feature[0] }}</span><h3>{{ $feature[1] }}</h3><p>{{ $feature[2] }}</p></article>@endforeach</div></div></section>

    <section id="wallet" class="section muted-section"><div class="shell two-col wallet-grid"><div><p class="eyebrow">Mobile Money</p><h2>Your money, connected to the way Africa pays.</h2><p class="lead">KEJVAULT is designed to work alongside the payment methods people already use every day.</p><div class="payment-grid"><span>Mobile Money</span><span>Mixx by Yas</span><span>Flooz</span><span>Banking and cards</span></div><small class="muted">Supported payment and withdrawal methods may vary by country.</small></div><div class="withdrawal"><div class="withdrawal-head"><div><small class="muted">KEJVAULT wallet - Demo</small><h3>Withdraw money</h3></div><span>W</span></div><label>Amount</label><div class="amount">250,000 <small>XOF</small></div><small class="muted">Withdraw to</small><div class="withdraw-options"><span>o Mixx by Yas</span><span>o Flooz</span><span>o Bank account</span></div><div class="fee"><span>Demo fee <b>2,500 XOF</b></span><strong>You receive <b>247,500 XOF</b></strong></div><button class="button full" disabled>Confirm withdrawal - Demo only</button><small class="fine-print">Illustrative amounts and fees only. No real transaction will occur.</small></div></div></section>

    <section class="section"><div class="shell"><p class="eyebrow">Use cases</p><h2>Built for African commerce.</h2><div class="use-grid">@foreach([['S','Social commerce','Instagram, Facebook, WhatsApp and TikTok deals.'],['M','Marketplaces','A secure payment layer for online marketplaces.'],['E','E-commerce','Protect payments from checkout to delivery.'],['+','Services','For freelancers, artisans and service providers.'],['U','Person-to-person','Safer deals with people you do not know personally.']] as $use)<article><span>{{ $use[0] }}</span><h3>{{ $use[1] }}</h3><p>{{ $use[2] }}</p></article>@endforeach</div></div></section>

    <section id="security" class="section security"><div class="shell two-col"><div><p class="eyebrow">Security and process</p><h2>Trust is built into every transaction.</h2><p class="lead">Your transaction. Your money. Your protection.</p></div><div class="security-list">@foreach(['Secure authentication','Transaction monitoring','Fraud prevention mechanisms','Encrypted communication','Transaction history','Identity verification where required','Dispute management','Account controls'] as $item)<span>OK {{ $item }}</span>@endforeach</div></div></section>

    <section class="section dispute"><div class="shell two-col"><div><p class="eyebrow">Dispute management</p><h2>When something goes wrong, there is a process.</h2><p class="lead">A transaction can be reported and reviewed under KEJVAULT rules. A review does not promise an automatic refund.</p><a href="#security" class="button outline">Learn about protection <span>-&gt;</span></a></div><div class="dispute-flow">@foreach(['Buyer','Reports issue','Review','Evidence','Resolution'] as $item)<span>{{ $item }}</span>@endforeach</div></div></section>

    <section id="business" class="section dark-section business"><div class="shell business-grid"><div><span class="business-icon">B</span><h2>Give your customers a reason to trust you.</h2><p>Receive secure payments, create payment links, track orders, see payment status, maintain digital records, and withdraw available funds.</p><a class="button button-primary" href="#top">For businesses <span>-&gt;</span></a></div><div><span class="business-icon green">API</span><h2>Build trust directly into your platform.</h2><p>A future integration layer for marketplaces and digital platforms: create transactions, secure funds, confirm delivery, release, refund, status, and webhooks.</p><a class="button button-ghost" href="#top">Explore the API <span>-&gt;</span></a></div></div></section>

    <section class="section africa"><div class="shell two-col"><div><p class="eyebrow">African-first</p><h2>Designed for Africa. Built for global commerce.</h2><p class="lead">KEJVAULT is being designed with the realities of African commerce in mind: mobile money, digital marketplaces, cross-border trade and growing online businesses.</p></div><div class="africa-map"><div class="map-lock">K<small>KEJVAULT</small></div><span>Commerce</span><span>Mobile Money</span><span>Marketplaces</span><span>Cross-border</span></div></div></section>

    <section class="cta"><div class="shell"><h2>Do not just make a payment.<br>Make a secure transaction.</h2><p>KEJVAULT is building a safer way to buy, sell and move money across African markets.</p><div><a class="button button-dark" href="#top">Join KEJVAULT <span>-&gt;</span></a><a class="button button-dark" href="#business">Become a partner</a></div></div></section>
</main>
<footer><div class="shell footer-grid"><div><a class="brand" href="#top"><span class="brand-mark">K</span> KEJVAULT</a><p>Secure the deal.<br>Protect the payment.</p></div><div><b>Product</b><a href="#how">How it works</a><a href="#wallet">Wallet</a><a href="#demo">Payments</a><a href="#security">Security</a></div><div><b>Business</b><a href="#business">For businesses</a><a href="#business">Partners</a><a href="#business">Payment links</a></div><div><b>Developers</b><a href="#business">API</a><a href="#business">Documentation</a><a href="#business">Webhooks</a></div><div><b>Company</b><a href="#top">About</a><a href="#top">Contact</a><a href="#top">Legal</a></div></div><div class="shell copyright">Copyright 2026 KEJVAULT. Concept website.</div></footer>
</body>
</html>
